name: Go Unit Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci-test-go:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-test-go
        uses: smartcontractkit/.github/actions/ci-test-go@ci-test-go/1.0.0
        with:
          # aws inputs
          aws-region: ${{ secrets.AWS_REGION }}
          # gati inputs
          use-gati: true
          aws-role-arn-gati: ${{ secrets.AWS_ROLE_ARN_GATI }}
          aws-lambda-url-gati: ${{ secrets.AWS_LAMBDA_URL_GATI }}
          # go inputs
          go-test-cmd: go test ./...
          use-go-cache: true